OENIK_PROG3_2019_2_EL29EK/MyF1.Web/Models/MotorGyartok.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyF1.Web.Models
{
    //Form Model
    public class MotorGyartok
    {
        [Display(Name ="Mgy Id")]
        [Required]
        public int Id { get; set; }
        [Display(Name = "Mgy Nev")]
        [Required]
        public string Nev { get; set; }
        [Display(Name = "Mgy AlapitasEve")]
        [Required]
        public int AlapitasEve { get; set; }
        [Display(Name = "Mgy Nemzetiseg")]
        [Required]
        public string Nemzetiseg { get; set; }
        [Display(Name = "Mgy Kozpont")]
        [Required]
        public string Kozpont { get; set; }
        [Display(Name = "Mgy LoEro")]
        [Required]
        public int LoEro { get; set; }
        [Display(Name = "Mgy GyozelmekSzama")]
        [Required]
        public int GyozelmekSzama { get; set; }
    }
}

OENIK_PROG3_2019_2_EL29EK/MyF1.Web/Models/MotorGyartokViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyF1.Web.Models
{
    public class MotorGyartokViewModel
    {
        public MotorGyartok EditedMGy { get; set; }
        public List<MotorGyartok> ListOfMGy { get; set; }
    }
}

OENIK_PROG3_2019_2_EL29EK/MyF1.Web/Controllers/MotorGyartokController.cs
using AutoMapper;
using MyF1.Data;
using MyF1.Logic;
using MyF1.Repository;
using MyF1.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyF1.Web.Controllers
{
    public class MotorGyartokController : Controller
    {
        ILogic logic;
        IMapper mapper;
        MotorGyartokViewModel vm;

        public MotorGyartokController()
        {
            AdatbazisEntities ctx = new AdatbazisEntities();
            Repository.Repository repo = new Repository.Repository(ctx);
            logic = new Logic.Logic(repo);
            mapper = MapperFactory.CreateMapper();
            vm = new MotorGyartokViewModel();
            vm.EditedMGy = new MotorGyartok();
            var motogy = logic.MotorgyartokGetAll();
            vm.ListOfMGy = mapper.Map<IQueryable<Data.motorGyartok>,List<Models.MotorGyartok>>(motogy);
        }

        private MotorGyartok GetMGyModel(int id)
        {
            motorGyartok oneMgy = logic.MotorGyartokGetOne(id);
            return mapper.Map<Data.motorGyartok, Models.MotorGyartok>(oneMgy);
        }

        // GET: MotorGyartok
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("MotorGyartoIndex",vm);
        }

        // GET: MotorGyartok/Details/5
        public ActionResult Details(int id)
        {
            return View("MotorGyartoDetails",GetMGyModel(id));
        }
        //GET: MotorGyartok/Remove/5
        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete Failed";
            if (logic.MotorGyDelete(id)) TempData["editResult"] = "Delete OK";

            return RedirectToAction(nameof(Index));
        }
        //GET: MotorGyartok/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedMGy = GetMGyModel(id);
            return View("MotorGyartoIndex", vm);
        }
        [HttpPost]
        public ActionResult Edit(MotorGyartok mgy,string editAction)
        {
            if (ModelState.IsValid && mgy!=null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction=="AddNew")
                {
                    logic.MotorGyartokCreate(mgy.Nev, mgy.AlapitasEve, mgy.Nemzetiseg, mgy.Kozpont, mgy.LoEro, mgy.GyozelmekSzama);
                }
                else
                {
                    bool siker = logic.MotorGyUpdate(mgy.Id, mgy.Nev, mgy.AlapitasEve, mgy.Nemzetiseg, mgy.Kozpont, mgy.LoEro, mgy.GyozelmekSzama);
                    if (!siker) TempData["editResult"] = "Edit Fail";

                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedMGy = mgy;
                return View("MotorGyartoIndex", vm);
            }
        }
        
    }
}

OENIK_PROG3_2019_2_EL29EK/MyF1.Web/Views/MotorGyartok/MotorGyartoDetails.cshtml
@model MyF1.Web.Models.MotorGyartok
@{
    ViewBag.Title = "MotorGyartoDetails";
}

<h2>Data shit of one car</h2>


@Html.ActionLink("Back to the list", "Index");
<table border="1">
    <tr>
        <td>The ID for the MotorGyarto</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nev)</td>
        <td>@Html.DisplayFor(m => m.Nev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.AlapitasEve)</td>
        <td>@Html.DisplayFor(m => m.AlapitasEve)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nemzetiseg)</td>
        <td>@Html.DisplayFor(m => m.Nemzetiseg)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Kozpont)</td>
        <td>@Html.DisplayFor(m => m.Kozpont)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LoEro)</td>
        <td>@Html.DisplayFor(m => m.LoEro)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.GyozelmekSzama)</td>
        <td>@Html.DisplayFor(m => m.GyozelmekSzama)</td>
    </tr>
</table>

OENIK_PROG3_2019_2_EL29EK/MyF1.Web/Views/MotorGyartok/MotorGyartoEdit.cshtml
@model MyF1.Web.Models.MotorGyartok
@{ 
    ViewBag.Title = "MotorgyartokEdit";
}

<h2>Eidt one motorgyarto</h2>

@using (Html.BeginForm("Edit", "MotorGyartok"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m=>m.Id)
    @Html.Hidden("editAction",ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Nev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.AlapitasEve)</div>
    <div class="editor-field">@Html.EditorFor(m => m.AlapitasEve)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Nemzetiseg)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nemzetiseg)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Kozpont)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Kozpont)</div>

    <div class="editor-label">@Html.LabelFor(m => m.LoEro)</div>
    <div class="editor-field">@Html.EditorFor(m => m.LoEro)</div>

    <div class="editor-label">@Html.LabelFor(m => m.GyozelmekSzama)</div>
    <div class="editor-field">@Html.EditorFor(m => m.GyozelmekSzama)</div>

    <input type="submit" value="Send" />
}

OENIK_PROG3_2019_2_EL29EK/MyF1.Web/Views/MotorGyartok/MotorGyartoIndex.cshtml
@model MyF1.Web.Models.MotorGyartokViewModel
@{
    ViewBag.Title = "MotorGyarto Index";
}

<h2>MotorGyarto Index</h2>

<p style="color:red;font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("MotorGyartoEdit",Model.EditedMGy)
@Html.Partial("MotorGyartoList",Model.ListOfMGy)

OENIK_PROG3_2019_2_EL29EK/MyF1.Web/Views/MotorGyartok/MotorGyartoList.cshtml
@model IEnumerable<MyF1.Web.Models.MotorGyartok>

@{ 
    ViewBag.Title = "MotorGyartokList";
}
<h2>List of Motorgyartok</h2>

@if (Model.Count() == 0)
{
    <p>Nincs adat az adatbázisban</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m=>m.First().Nev)</th>
            <th>@Html.DisplayNameFor(m => m.First().Kozpont)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.Nev)</td>
            <td>@Html.DisplayFor(m => item.Kozpont)</td>
            <td>@Html.ActionLink("[SHOW]","Details",new { id = item.Id })</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>

        </tr>
        }
    </table>
}